<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath>../Build/Bin</OutputPath>
    <NoWarn>$(NoWarn);CS8600;CS8601;CS8602;CS8604;CS8605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Engine">
      <HintPath>..\Build\Bin\net10.0\Engine.dll</HintPath>
    </Reference>
    <PackageReference Include="Silk.NET.Assimp" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Shaderc" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
  </ItemGroup>
</Project>
